$NameList = @(
"2001: A Space Odyssey",
"300",
"A Christmas Story",
"A Nightmare on Elm Street (2010)",
"Alice in Wonderland (2010)",
"Alien: Covenant",
"American Psycho",
"Arrival",
"Back to the Future",
"Back to the Future II",
"Back to the Future Part III",
"Batman Begins",
"Blade Runner 2049",
"Blade Runner: The Final Cut",
"Constantine",
"Contact",
"Cosmos: A Spacetime Odyssey Season 1",
"Cosmos: Possible Worlds",
"Divergent",
"Donnie Darko",
"Dr. Seuss' How the Grinch Stole Christmas",
"Dune",
"Ex Machina",
"Fight Club",
"Forrest Gump",
"Get Rich Or Die Tryin'",
"Good Will Hunting",
"Grandma's Boy UNRATED",
"Harry Potter and the Chamber of Secrets",
"Harry Potter and the Deathly Hallows: Part 1",
"Harry Potter and the Deathly Hallows: Part 2",
"Harry Potter and the Goblet of Fire",
"Harry Potter and the Half-Blood Prince",
"Harry Potter and the Order of the Phoenix",
"Harry Potter and the Prisoner of Azkaban",
"Harry Potter and the Sorcerer's Stone",
"Home Alone",
"Home Alone 2: Lost In New York",
"Inglorious Basterds",
"Interstellar",
"IT",
"IT Chapter Two",
"It Follows",
"Jacob's Ladder",
"John Wick",
"Jurassic Park",
"Life of Pi",
"Limitless",
"Margin Call",
"Meet Joe Black",
"Men in Black",
"Moneyball",
"Mr. Nobody (Extended Director's Cut)",
"Napoleon Dynamite",
"October Sky",
"Prisoners",
"Prometheus",
"Pulp Fiction",
"Rise of the Planet of the Apes",
"Seven (1995)",
"Shrek",
"Shrek 2",
"Shrek Forever After",
"Shrek the Third",
"Snowpiercer",
"Spaceballs",
"Spider-Man: Into The Spider-Verse",
"Succession - Season 1",
"Succession: The Complete Second Season",
"Succession: The Complete Third Season",
"Superbad Unrated",
"The Batman",
"The Big Lebowski",
"The Big Short",
"The Book of Eli",
"The Dark Knight",
"The Dark Knight Rises",
"The Fast & Furious: Tokyo Drift",
"The Goonies",
"The Green Mile",
"The Hobbit",
"The House That Jack Built (Director's Cut)",
"THE HUNGER GAMES",
"The Invisible Man (2020)",
"The Lord of The Rings",
"The Matrix",
"The Matrix Reloaded",
"The Matrix Revolutions",
"The Notebook",
"The Office Season 1",
"The Office Season 2",
"The Office Season 3",
"The Office Season 4",
"The Office Season 5",
"The Office Season 6",
"The Outsiders",
"The Pursuit of Happyness",
"The Shawshank Redemption",
"The Strangers")

Get-Random -InputObject $NameList